export const siteMap = [
  {
    keywords: ["home", "rizzi", "welcome", "luxury", "lifestyle", "innovation"],
    url: "/",
  },
  {
    keywords: [
      "about",
      "our evolution",
      "luxury",
      "lifestyle",
      "innovation",
      "headquarters",
      "Dubai",
      "gold",
      "gems",
      "jewelry",
      "watches",
      "perfumes",
      "cosmetics",
      "baby care",
      "fashion",
      "home décor",
      "premium services",
      "mission",
      "vision",
      "brand family",
      "Luvnor",
      "Jewelsmi",
      "Luvra",
      "AirFeri",
    ],
    url: "/about",
  },
  {
    keywords: [
      "terms",
      "conditions",
      "user obligations",
      "account security",
      "lawful use",
      "products",
      "services",
      "intellectual property",
      "copyright",
      "governing law",
      "jurisdiction",
      "Dubai courts",
      "contact info",
      "email",
      "phone",
    ],
    url: "/terms-and-conditions",
  },
  {
    keywords: [
      "careers",
      "job opportunities",
      "explore jobs",
      "employment",
      "professional journey",
      "legacy of excellence",
      "growth",
    ],
    url: "/careers",
  },
  {
    keywords: [
      "open positions",
      "job openings",
      "submit CV",
      "candidate form",
      "contact HR",
      "exceptional talent",
      "recruitment",
      "careers",
    ],
    url: "/careers/openings",
  },
  {
    keywords: [
      "contact",
      "full name",
      "mobile number",
      "email",
      "address",
      "city",
      "country",
      "message",
      "submit form",
      "meet us",
      "call us",
      "email us",
      "location",
      "Kalmunai",
      "Sri Lanka",
      "Google Map",
    ],
    url: "/contactUs",
  },
];
